name: myapp
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.1.8+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.8.1
  go_router: ^13.2.0
  package_info_plus: ^8.1.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
