name: myapp
description: "A new Flutter project."
publish_to: "none"

version: 1.1.8+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  go_router: ^13.2.0
  package_info_plus: ^8.1.2
  speech_to_text: ^7.0.0
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  youtube_explode_dart: ^2.3.10
  flutter_widget_from_html: ^0.16.0
  path_provider: ^2.1.5
  flutter_archive: ^6.0.3
  freezed_annotation: ^2.4.4
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - .env
