// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeZPce-mukcLx_mUnt0nXz_AE3GI0HWtM',
    appId: '1:731914931196:web:9f92693335eee6c7508079',
    messagingSenderId: '731914931196',
    projectId: 'english-course-app-a5396',
    authDomain: 'english-course-app-a5396.firebaseapp.com',
    storageBucket: 'english-course-app-a5396.firebasestorage.app',
    measurementId: 'G-WZ5CHJ6MWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufcdDuso7mnf-fm0rkLbs1xsWh77Pn9A',
    appId: '1:731914931196:android:c54ab15cb438c76c508079',
    messagingSenderId: '731914931196',
    projectId: 'english-course-app-a5396',
    storageBucket: 'english-course-app-a5396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPNxpLeITLBdkfstDsU_5-CJHLGDRRkc',
    appId: '1:731914931196:ios:8553d8280c6d159f508079',
    messagingSenderId: '731914931196',
    projectId: 'english-course-app-a5396',
    storageBucket: 'english-course-app-a5396.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
